apiVersion: apps/v1
kind: Deployment
metadata:
  name: scg-backend-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scg-be
  template:
    metadata:
      labels:
        app: scg-be
    spec:
      containers:
      - name: be-v2-container
        image: scgskku/scg-home-be-prod:48f0574a56c8ce0cf515369a599c602e5fbf3ad5-28640797148-1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: TZ
          value: "Asia/Seoul"
