apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scg-ingress-be
spec:
  ingressClassName: nginx
  rules:
  - host: api.scg.skku.ac.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scg-be
            port:
              number: 9002
  tls: 
    - hosts:
      - api.scg.skku.ac.kr
      secretName: gitops-tls
status:
  LoadBalancer:
    - ip: 115.145.150.214