apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scg-ingress-fe
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-clusterissuer"
spec:
  ingressClassName: nginx
  rules:
  - host: scg.skku.ac.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scg-frontend-svc
            port:
              number: 8000
  tls: 
    - hosts:
      - scg.skku.ac.kr
      secretName: gitops-tls
    