apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scg-ingress-fe
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: fe.scg.skku.ac.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scg-frontend-svc
            port:
              number: 8000
  tls: 
    - hosts:
      - fe.scg.skku.ac.kr
      secretName: gitops-tls
    